import pandas as pd
import ast

# ================= 1. 配置区 =================
INPUT_FILE = "/Users/gzy2520/Desktop/lac/filter/symbol_and_pathway.csv"  # 原始文件
OUTPUT_FILE = "/Users/gzy2520/Desktop/lac/filter/venn_input.csv"  # 输出文件

# umap_5type.py 的分类逻辑
EXACT_MAP = {
    "NER": {
        "DACOSTA_UV_RESPONSE_VIA_ERCC3_COMMON_DN", "DACOSTA_UV_RESPONSE_VIA_ERCC3_DN",
        "DACOSTA_UV_RESPONSE_VIA_ERCC3_TTD_UP", "DACOSTA_UV_RESPONSE_VIA_ERCC3_UP",
        "DAZARD_RESPONSE_TO_UV_NHEK_DN", "DAZARD_RESPONSE_TO_UV_NHEK_UP",
        "DAZARD_RESPONSE_TO_UV_SCC_DN", "DAZARD_UV_RESPONSE_CLUSTER_G5",
        "DAZARD_UV_RESPONSE_CLUSTER_G6", "ENK_UV_RESPONSE_EPIDERMIS_DN",
        "ENK_UV_RESPONSE_EPIDERMIS_UP", "ENK_UV_RESPONSE_KERATINOCYTE_DN",
        "ENK_UV_RESPONSE_KERATINOCYTE_UP", "GCM_ERCC4", "GENTILE_UV_HIGH_DOSE_DN",
        "GENTILE_UV_LOW_DOSE_DN", "GENTILE_UV_RESPONSE_CLUSTER_D4",
        "GENTILE_UV_RESPONSE_CLUSTER_D5", "GENTILE_UV_RESPONSE_CLUSTER_D6",
        "GENTILE_UV_RESPONSE_CLUSTER_D8", "GOBP_NUCLEOTIDE_EXCISION_REPAIR",
        "GOBP_PYRIMIDINE_DIMER_REPAIR", "GOBP_TRANSCRIPTION_COUPLED_NUCLEOTIDE_EXCISION_REPAIR",
        "GOBP_UV_DAMAGE_EXCISION_REPAIR", "HP_DEFECTIVE_DNA_REPAIR_AFTER_ULTRAVIOLET_RADIATION_DAMAGE",
        "KEGG_NUCLEOTIDE_EXCISION_REPAIR", "MURAKAMI_UV_RESPONSE_6HR_UP",
        "REACTOME_DNA_DAMAGE_RECOGNITION_IN_GG_NER",
        "REACTOME_FORMATION_OF_TRANSCRIPTION_COUPLED_NER_TC_NER_REPAIR_COMPLEX",
        "REACTOME_GAP_FILLING_DNA_REPAIR_SYNTHESIS_AND_LIGATION_IN_GG_NER",
        "REACTOME_GLOBAL_GENOME_NUCLEOTIDE_EXCISION_REPAIR_GG_NER",
        "REACTOME_NUCLEOTIDE_EXCISION_REPAIR",
        "REACTOME_REPAIR_SYNTHESIS_FOR_GAP_FILLING_BY_DNA_POL_IN_TC_NER",
        "REACTOME_TRANSCRIPTION_COUPLED_NUCLEOTIDE_EXCISION_REPAIR_TC_NER",
        "WP_NUCLEOTIDE_EXCISION_REPAIR", "WP_NUCLEOTIDE_EXCISION_REPAIR_IN_XERODERMA_PIGMENTOSUM"
    },
    "HR": {
        "BAE_BRCA1_TARGETS_DN", "BAE_BRCA1_TARGETS_UP", "BIOCARTA_ATRBRCA_PATHWAY",
        "GOBP_DOUBLE_STRAND_BREAK_REPAIR_VIA_SINGLE_STRAND_ANNEALING",
        "GOBP_DOUBLE_STRAND_BREAK_REPAIR_VIA_SYNTHESIS_DEPENDENT_STRAND_ANNEALING",
        "GOBP_HOMOLOGOUS_RECOMBINATION", "GOBP_MITOTIC_RECOMBINATION",
        "GOBP_NEGATIVE_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_HOMOLOGOUS_RECOMBINATION",
        "GOBP_POSITIVE_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_HOMOLOGOUS_RECOMBINATION",
        "GOBP_POSITIVE_REGULATION_OF_DNA_RECOMBINATION", "GOBP_RECOMBINATIONAL_REPAIR",
        "GOBP_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_HOMOLOGOUS_RECOMBINATION",
        "GOBP_REPLICATION_BORN_DOUBLE_STRAND_BREAK_REPAIR_VIA_SISTER_CHROMATID_EXCHANGE",
        "HONRADO_BREAST_CANCER_BRCA1_VS_BRCA2", "KEGG_HOMOLOGOUS_RECOMBINATION",
        "MACLACHLAN_BRCA1_TARGETS_UP", "REACTOME_HOMOLOGOUS_DNA_PAIRING_AND_STRAND_EXCHANGE",
        "REACTOME_HOMOLOGOUS_RECOMBINATION_REPAIR_OF_REPLICATION_INDEPENDENT_DOUBLE_STRAND_BREAKS",
        "REACTOME_HOMOLOGY_DIRECTED_REPAIR", "VANTVEER_BREAST_CANCER_BRCA1_UP"
    },
    "NHEJ": {
        "COLLIS_PRKDC_REGULATORS", "COLLIS_PRKDC_SUBSTRATES", "GNF2_XRCC5",
        "GOBP_DOUBLE_STRAND_BREAK_REPAIR_VIA_ALTERNATIVE_NONHOMOLOGOUS_END_JOINING",
        "GOBP_DOUBLE_STRAND_BREAK_REPAIR_VIA_CLASSICAL_NONHOMOLOGOUS_END_JOINING",
        "GOBP_DOUBLE_STRAND_BREAK_REPAIR_VIA_NONHOMOLOGOUS_END_JOINING",
        "GOBP_NEGATIVE_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_NONHOMOLOGOUS_END_JOINING",
        "GOBP_POSITIVE_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_NONHOMOLOGOUS_END_JOINING",
        "GOBP_REGULATION_OF_DOUBLE_STRAND_BREAK_REPAIR_VIA_NONHOMOLOGOUS_END_JOINING",
        "GOCC_DNA_DEPENDENT_PROTEIN_KINASE_COMPLEX",
        "GOCC_DNA_DEPENDENT_PROTEIN_KINASE_DNA_LIGASE_4_COMPLEX",
        "GOCC_NONHOMOLOGOUS_END_JOINING_COMPLEX", "KEGG_NON_HOMOLOGOUS_END_JOINING",
        "MORF_XRCC5"
    },
    "BER": {
        "GCM_APEX1", "GNF2_APEX1", "GOBP_BASE_EXCISION_REPAIR",
        "GOBP_BASE_EXCISION_REPAIR_GAP_FILLING", "GOBP_DNA_ALKYLATION_REPAIR",
        "GOMF_DNA_APURINIC_OR_APYRIMIDINIC_SITE_ENDONUCLEASE_ACTIVITY",
        "GOMF_DNA_N_GLYCOSYLASE_ACTIVITY", "KEGG_BASE_EXCISION_REPAIR",
        "REACTOME_BASE_EXCISION_REPAIR",
        "REACTOME_PCNA_DEPENDENT_LONG_PATCH_BASE_EXCISION_REPAIR",
        "REACTOME_POLB_DEPENDENT_LONG_PATCH_BASE_EXCISION_REPAIR",
        "REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE",
        "WP_BASE_EXCISION_REPAIR"
    },
    "CP": {
        "BIOCARTA_ATM_PATHWAY", "BIOCARTA_G1_PATHWAY", "BIOCARTA_G2_PATHWAY",
        "BIOCARTA_P53HYPOXIA_PATHWAY", "DNA_DAMAGE_CHECKPOINT",
        "GOBP_DNA_DAMAGE_RESPONSE_SIGNAL_TRANSDUCTION_BY_P53_CLASS_MEDIATOR",
        "GOBP_DNA_INTEGRITY_CHECKPOINT_SIGNALING",
        "GOBP_DNA_REPLICATION_CHECKPOINT_SIGNALING",
        "GOBP_MITOTIC_DNA_INTEGRITY_CHECKPOINT_SIGNALING",
        "GOBP_MITOTIC_INTRA_S_DNA_DAMAGE_CHECKPOINT_SIGNALING",
        "GOBP_POSITIVE_REGULATION_OF_DNA_DAMAGE_RESPONSE_SIGNAL_TRANSDUCTION_BY_P53_CLASS_MEDIATOR",
        "GOBP_REGULATION_OF_DNA_DAMAGE_CHECKPOINT",
        "GOBP_REGULATION_OF_DNA_DAMAGE_RESPONSE_SIGNAL_TRANSDUCTION_BY_P53_CLASS_MEDIATOR",
        "GOBP_SIGNAL_TRANSDUCTION_IN_RESPONSE_TO_DNA_DAMAGE", "INGA_TP53_TARGETS",
        "KANNAN_TP53_TARGETS_UP", "KEGG_CELL_CYCLE", "KEGG_P53_SIGNALING_PATHWAY",
        "PEREZ_TP53_TARGETS", "REACTOME_G1_S_DNA_DAMAGE_CHECKPOINTS",
        "REACTOME_G2_M_DNA_DAMAGE_CHECKPOINT",
        "REACTOME_P53_INDEPENDENT_G1_S_DNA_DAMAGE_CHECKPOINT",
        "SCHAVOLT_TARGETS_OF_TP53_AND_TP63",
        "SCIAN_CELL_CYCLE_TARGETS_OF_TP53_AND_TP73_UP",
        "TANG_SENESCENCE_TP53_TARGETS_DN", "WHITFIELD_CELL_CYCLE_G2",
        "WHITFIELD_CELL_CYCLE_G2_M", "WHITFIELD_CELL_CYCLE_M_G1",
        "WP_DNA_DAMAGE_RESPONSE", "WP_DNA_IRDAMAGE_AND_CELLULAR_RESPONSE_VIA_ATR",
        "WP_DNA_IRDOUBLE_STRAND_BREAKS_AND_CELLULAR_RESPONSE_VIA_ATM",
        "ZHOU_CELL_CYCLE_GENES_IN_IR_RESPONSE_24HR",
        "ZHOU_CELL_CYCLE_GENES_IN_IR_RESPONSE_6HR"
    }
}

FUZZY_KEYWORDS = {
    "HR": ["HOMOLOGOUS RECOMBINATION", "HR", "BRCA", "RAD51", "RAD52", "DSB REPAIR"],
    "BER": ["BASE EXCISION REPAIR", "BER", "PARP", "APEX", "XRCC1"],
    "NHEJ": ["NON-HOMOLOGOUS END JOINING", "NHEJ", "XRCC5", "XRCC6", "PRKDC", "DNA-PK"],
    "CP": ["CHECKPOINT", "ATM", "ATR", "CHEK", "TP53", "P53", "CELL CYCLE ARREST"],
    "NER": ["NUCLEOTIDE EXCISION REPAIR", "NER", "ERCC", "XPC", "DDB2", "UV REPAIR"]
}


# ================= 2. 逻辑处理 =================
def process():
    print(f"正在读取: {INPUT_FILE}")
    try:
        df = pd.read_csv(INPUT_FILE, encoding="utf-8-sig")
    except:
        df = pd.read_csv(INPUT_FILE, encoding="gbk")

    # 解析 Pathway 字符串
    def parse_pathways(val):
        try:
            return [x.strip().upper() for x in ast.literal_eval(val)]
        except:
            s = str(val).strip().upper()
            return [s] if s and s != 'NAN' else []

    df["PATHWAY_LIST"] = df["STANDARD_NAME"].apply(parse_pathways)

    # 预处理精确匹配
    EXACT_MAP_UPPER = {k: {x.upper() for x in v} for k, v in EXACT_MAP.items()}

    # 判断每个基因属于哪个类别 (Binary 1/0)
    def get_binary_class(pathways):
        res = {k: 0 for k in EXACT_MAP.keys()}
        for p in pathways:
            matched = False
            # 优先精确匹配
            for cat, p_set in EXACT_MAP_UPPER.items():
                if p in p_set:
                    res[cat] = 1
                    matched = True
                    break
                    # 模糊匹配兜底
            if not matched:
                for cat, keywords in FUZZY_KEYWORDS.items():
                    if any(kw in p for kw in keywords):
                        res[cat] = 1
                        matched = True
                        break
        return res

    print("正在进行分类匹配...")
    count_data = df["PATHWAY_LIST"].apply(get_binary_class).tolist()
    categories = list(EXACT_MAP.keys())
    count_df = pd.DataFrame(count_data, columns=categories)

    # 合并结果
    final_df = pd.concat([df["Symbol"], count_df], axis=1)

    # 保存
    final_df.to_csv(OUTPUT_FILE, index=False)
    print(f"已生成 {OUTPUT_FILE}")


if __name__ == "__main__":
    process()